# Generated by Django 4.2.7 on 2023-11-17 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Временная метка')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('desc', models.CharField(max_length=200, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Фотография')),
                ('status_app', models.CharField(choices=[('Н', 'Новая'), ('П', 'Принята в работу'), ('В', 'Выполнено')], default='Н', max_length=1, verbose_name='Статус заявки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
