# Generated by Django 4.2.7 on 2023-11-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='image',
            new_name='image_app',
        ),
    ]
